### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by jschoch** [adafruit/Adafruit_APDS9960#2]
does this work with the esp32?  I have not been able to get the sensor to respond though i can get it to work on an Uno.

**Comment by ladyada** [comment]
@deanm1278 wanna try it?

**Comment by jschoch** [comment]
Thanks for taking this on!!!  Glad to see it seems to be a bug in the ESP arduino lib and not the adafruit lib!

**Comment by jschoch** [comment]
any workaround for this?

**Comment by ladyada** [comment]
nope. you can ask espressif for updates - we're using the standard i2c library and there's no other API really

future-reading people: do not post "me too!"'s, we have no control over the esp32 i2c library :) please post only if you have a fix

thx!

**Comment by jschoch** [comment]
perhaps using twowire per the suggestion below helps?  If you think it does I can take a stab at trying to implement it.

https://github.com/espressif/arduino-esp32/issues/977

**Comment by deanm1278** [comment]
Hey checking in on this issue because it's old. Has this been solved yet?
