### ISSUE TITLE
gconf1::get() is incorrect.

### ISSUE THREAD

**Issue by GuyCarver** [adafruit/Adafruit_APDS9960#7]
Is:
		uint8_t get(){
			return (GFIFOTH << 7) | (GEXMSK << 5) | GEXPERS;
Should be:
		uint8_t get(){
			return (GFIFOTH << 6) | (GEXMSK << 2) | GEXPERS;

**Comment by ladyada** [comment]
@deanm1278 heya check it? :)

**Comment by janekm** [comment]
I concur. Looks like a typo from reading the offsets off the datasheet.

**Comment by deanm1278** [comment]
fixed!
